### ISSUE TITLE
It should give clearer/better error messages.

### ISSUE THREAD

**Issue by YazeedAlsaif** [swapagarwal/pm#5]
Hello, thank you for you work. :+1:

I just think it should give better messages in ~/.pm.log.

When I tried it, it said: `./pm: line 37: expect: command not found`. Which would only made sense because I read that it requires `expect` to work.

**Comment by swapagarwal** [comment]
I agree that this error message can be ambiguous. However, this error is thrown by the shell itself. I think it can be helpful if you set this in your environment: `export COMMAND_NOT_FOUND_INSTALL_PROMPT=1`
